# Generated by Django 6.0.6 on 2026-07-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='message',
            new_name='text',
        ),
    ]
